# defaults: &defaults
#   host: 127.0.0.1
#   port: 6379
defaults: &defaults
  host: redis
  port: 6379

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
