# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ed7b03d64b63842e5c8d788da8e832397207b672207011aaf2cb08c21df3c8db8393dd4f1658f5f001ef4e60c0feafd72b3d2f4ee9ca3d3accf656864d6a1b7

test:
  secret_key_base: ac1265d3cc02137b47005f81cb19e82d00f833310cde4ad96cb4c2a8e08db09b9ce50b478fcaa0b41dbc6b6d81c75fbbec03db4095fa0cd35cdf446712e8150a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
